==5188== Invalid read of size 8
==5188==    at 0x405699: socioTPrestamo(rep_prestamo*) (prestamo.cpp:51)
==5188==    by 0x407A41: disponibleLibroTBiblioteca(rep_biblioteca*, int) (biblioteca.cpp:58)
==5188==    by 0x4047FD: main_disponibleLibroBiblioteca(rep_biblioteca*) (principal.cpp:1598)
==5188==    by 0x401909: main (principal.cpp:549)
==5188==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==5188== 
==5188== 
==5188== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==5188==  Access not within mapped region at address 0x0
==5188==    at 0x405699: socioTPrestamo(rep_prestamo*) (prestamo.cpp:51)
==5188==    by 0x407A41: disponibleLibroTBiblioteca(rep_biblioteca*, int) (biblioteca.cpp:58)
==5188==    by 0x4047FD: main_disponibleLibroBiblioteca(rep_biblioteca*) (principal.cpp:1598)
==5188==    by 0x401909: main (principal.cpp:549)
==5188==  If you believe this happened as a result of a stack
==5188==  overflow in your program's main thread (unlikely but
==5188==  possible), you can try to increase the size of the
==5188==  main thread stack using the --main-stacksize= flag.
==5188==  The main thread stack size used in this run was 8388608.
timeout: la orden monitorizada ha volcado un 'core'
